blogs: 
  - title: "竹林里有冰的博客"
    url: "https://zhul.in"
    feed: "https://zhul.in/rss.xml"
  
  - title: "J10c's site"
    url: "https://site.j10ccc.xyz/"
    feed: "https://site.j10ccc.xyz/zh-cn/blog/rss.xml"
  
  - title: "派大星的石头屋"
    url: "https://blog.cnpatrickstar.com/"
    feed: "https://blog.cnpatrickstar.com/index.xml"
  
  - title: "Node Sans Blog"
    url: "https://blog.node189.top/"
    feed: "https://blog.node189.top/rss.xml"

  - title: "i1nfo"
    url: "https://blog.i1nfo.com/"
    feed: "https://blog.i1nfo.com/atom.xml"

  - title: "Finley's Blog"
    url: "https://www.f1nley.xyz/"
    feed: "https://www.f1nley.xyz/blog/rss.xml"

  - title: "Mulberror's Blog"
    url: "https://blog.mulbx.top/"
    feed: "https://blog.mulbx.top/index.xml"

  - title: "Tiancy's Blog"
    url: "https://blog.tiancy.cn/"
    feed: "https://blog.tiancy.cn/atom.xml"

  - title: "Hygge's Blog"
    url: "https://ljw030710.github.io/"
    feed: "https://ljw030710.github.io/atom.xml"

  - title: "消失在彩霞里的博客"
    url: "https://blog.aiyin.club/"
    feed: "https://blog.aiyin.club/index.xml"
    
  - title: "T-ON-Y的博客"
    url: "https://tonywu.top/"
    feed: "https://tonywu.top/atom.xml"
