blogs:
  - title: "竹林里有冰的博客"
    url: "https://zhul.in"
    feed: "https://zhul.in/rss.xml"

  - title: "J10c's site"
    url: "https://site.j10c.cc/"
    feed: "https://site.j10c.cc/zh-cn/blog/rss.xml"

  - title: "派大星的石头屋"
    url: "https://blog.cnpatrickstar.com/"
    feed: "https://blog.cnpatrickstar.com/index.xml"

  - title: "Node Sans Blog"
    url: "https://blog.node189.top/"
    feed: "https://blog.node189.top/rss.xml"

  - title: "i1nfo"
    url: "https://blog.i1nfo.com/"
    feed: "https://blog.i1nfo.com/atom.xml"

  - title: "Finley's Blog"
    url: "https://www.f1nley.xyz/"
    feed: "https://www.f1nley.xyz/blog/rss.xml"

  - title: "Mulberror's Blog"
    url: "https://blog.mulbry.top/"
    feed: "https://blog.mulbry.top/index.xml"

  - title: "Tiancy's Blog"
    url: "https://blog.tiancy.cn/"
    feed: "https://blog.tiancy.cn/atom.xml"

  - title: "Hygge's Blog"
    url: "https://ljw030710.github.io/"
    feed: "https://ljw030710.github.io/atom.xml"

  - title: "消失在彩霞里的博客"
    url: "https://blog.tidechoir.cn/"
    feed: "https://blog.tidechoir.cn/index.xml"

  - title: "T-ON-Y的博客"
    url: "https://tonywu.top/"
    feed: "https://tonywu.top/atom.xml"

  - title: "白糖的记事本"
    url: "https://blog.sugarmgp.cn/"
    feed: "https://blog.sugarmgp.cn/rss2.xml"

  - title: "浅浅子の小屋"
    url: "https://blog.qianqianzyk.top/"
    feed: "https://blog.qianqianzyk.top/rss.xml"

  - title: "MangoGovo's blog"
    url: "https://blog.mggovo.cn/"
    feed: "https://blog.mggovo.cn/rss2.xml"

  - title: "望舒的尘歌壶"
    url: "https://blog.phlin.cn/"
    feed: "https://blog.phlin.cn/rss2.xml"

  - title: "青鸟のBlog"
    url: "https://blog.bluebird.icu/"
    feed: "https://blog.bluebird.icu/posts/index.xml"

  - title: "惜寞的无人小间"
    url: "https://www.lonesome.cn/"
    feed: "https://www.lonesome.cn/atom.xml"

  - title: "树下集熵"
    url: "https://www.entropy-tree.top/"
    feed: "https://www.entropy-tree.top/atom.xml"

  - title: "Mai's blog"
    url: "https://blog.imjh.xyz"
    feed: "https://blog.imjh.xyz/atom.xml"

  - title: "折乙 - blog"
    url: "https://zheyi.in"
    feed: "https://zheyi.in/rss.xml"
